name: midi_packed_data
description: A Dart package for reading and writing packed MIDI data.
version: 1.0.0
repository: https://github.com/intonarumori/midi_packed_data

environment:
  sdk: ^3.5.1

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
